export declare const NAME = "any";
export declare const CONFIG_FILE_NAME: string;
export declare const GREEN = "#07c160";
export declare const CWD: string;
export declare const ROOT: string;
export declare const ES_DIR: string;
export declare const LIB_DIR: string;
export declare const SITE_DIST_DIR: string;
export declare const CONFIG_FILE: string;
export declare const PACKAGE_JSON_FILE: string;
export declare const ROOT_WEBPACK_CONFIG_FILE: string;
export declare const ROOT_POSTCSS_CONFIG_FILE: string;
export declare const CACHE_DIR: string;
export declare const DIST_DIR: string;
export declare const CONFIG_DIR: string;
export declare const BABEL_CONFIG_FILE: string;
export declare const POSTCSS_CONFIG_FILE: string;
export declare const SCRIPT_EXTS: string[];
export declare const STYLE_EXTS: string[];
export declare const ENTRY_EXTS: string[];
export declare function requireNoCache(filepath: string): any;
export declare function getPackageJson(): any;
export declare function getConfig(): any;
export declare const SRC_DIR: any;
export declare const CSS_LANG: any;
export declare const FRAMEWORk: any;
export declare const STYLE_DIR: string;
