export * from './is';
export declare type NodeEnv = 'development' | 'production';
export declare type ModuleEnv = 'esmodule' | 'commonjs';
export declare function setNodeEnv(value: NodeEnv): void;
export declare function setModuleEnv(value: ModuleEnv): void;
export declare function hasYarn(): boolean;
export declare const EXT_REGEXP: RegExp;
export declare function replaceExt(path: string, ext: string): string;
export declare function getComponents(): string[];
export declare function camelize(str: string): string;
export declare function pascalize(str: string): string;
